### ISSUE TITLE
Weird situation with PATH variable

### ISSUE THREAD

**Issue by sw1tchdev** [kropp/intellij-makefile#193] opened 2020-11-10 09:54 UTC
Hello, thanks for plugin, i have a issue when i use Makefile plugin on **MacOS 10.15.7; Webstorm 2020.2.3** 
Example Makefile:
```
show_path:
	echo "$(PATH)"
```
When option **"Add 'node_modules/.bin' from the project root to $PATH"** in **Preferences > Tools > Terminal** is **enabled**, i run show_path from ide via makefile plugin, and output is:
```
echo "/Users/{path_to_my_project}/node_modules/.bin:null"
/Users/{path_to_my_project}/node_modules/.bin:null
```
I expected a normal output of `$PATH` variable, this behavior makes me no able to run other scripts (ex. docker-compose) from ide via makefile plugin. If i execute from ide terminal `make show_path`, `$PATH` is ok. 

When option **"Add 'node_modules/.bin' from the project root to $PATH"** in **Preferences > Tools > Terminal** is **disabled**, `$PATH` variable is ok (like a system `$PATH`), but without node_modules/.bin in `$PATH` (in ide runner and ide terminal) and i cant simple execute scripts from `node_modules/.bin`

**Comment by kropp** [comment] 2020-11-29 19:36
Duplicate of #186

**Closed as completed by kropp** 2020-11-29 19:36 UTC
