### ISSUE TITLE
[1.6] Invalid run configuration when run from a gutter: makefile's name is empty

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#87] opened 2019-01-08 23:50 UTC
I just upgraded to 1.6, and now, when I run a target from a gutter, it's run with an empty makefile name: `/usr/bin/make -f "" my-carget`.
The field in the generated run configuration is empty too.

The current makefile's name is not `Makefile`.

**Comment by kropp** [comment] 2019-01-09 21:37
Hi @singalen 
Unfortunately, I can't reproduce this issue and it doesn't seem to be related to the recent update.
There are several cases when the detected filename can be empty: `configuration.filename = context.location?.virtualFile?.path ?: ""`
A wild guess: is the file hidden or excluded from the project?

**Comment by singalen** [comment] 2019-01-10 17:21
Nope, the file is in the project.
After some time, this stopped reproducing for me as well.
Maybe this was caused by a stale piece of configuration - I'm not sure.

**Comment by kropp** [comment] 2019-01-10 22:04
I'm closing this issue then.
Please feel free to reopen with steps to reproduce, if you experience it again.

**Closed as completed by kropp** 2019-01-10 22:04 UTC
