### ISSUE TITLE
$(patsubst %,build-module-%,$(ALL_MODULES)) not supported

### ISSUE THREAD

**Issue by sonersivri** [kropp/intellij-makefile#116] opened 2020-01-20 10:26 UTC

**Comment by singalen** [comment] 2020-01-27 23:38
Can you add more detail? If I were the author, I wouldn't be able to understand what is the problem here.
What makefile you have, what is the expected behavior, what are you getting instead?

**Comment by singalen** [comment] 2020-01-27 23:38
Can you add more detail? If I were the author, I wouldn't be able to understand what is the problem here.
What makefile you have, what is the expected behavior, what are you getting instead?

**Comment by enerjazzer** [comment] 2020-02-06 09:04
It's likely a duplicate of https://github.com/kropp/intellij-makefile/issues/115

**Closed as completed** 2020-03-21 19:25 UTC

**Comment by sonersivri** [comment] 2020-04-05 20:05
commit fixed this issue thanks
